platform :ios, "8.0"
use_frameworks!

target 'xbsz' do
#    pod 'ReactiveCocoa' , '2.5'
    pod 'Masonry'
#    pod 'Realm'
    pod 'IDMPhotoBrowser'
    pod 'FMDB'
    pod 'AFNetworking'
    pod 'YYCategories'
    pod 'TZImagePickerController'
    pod 'YYModel'
    pod 'FDFullscreenPopGesture'
    pod 'IQKeyboardManager'
    pod 'MJRefresh'
    pod 'DZNEmptyDataSet'
    pod 'YYText'
    pod 'YYWebImage'
    pod 'SVProgressHUD'
    pod 'Bugly'
#    pod 'SDWebImage', '~> 3.7.1'
    #社会化分享与授权登录组件
    pod 'UMengUShare/Plugin/IDFA'
    pod 'UMengUShare/Social/ReducedWeChat'
    pod 'UMengUShare/Social/ReducedQQ'
    pod 'UMengUShare/Social/ReducedSina'

    
end
